---
stages:
  - test
  - release
  - build
  - integration-test

jsonlint:
  stage: test
  image: registry.gitlab.com/pipeline-components/jsonlint:latest
  script:
    - |
      find . -not -path './.git/*' -name '*.json' -type f -print0 |
      parallel --will-cite -k -0 -n1 jsonlint -q

.go_template_defaults:
  stage: test
.semver_template_defaults:
  stage: release
variables:
  SEMVER_PREFIX: v
include:
  - remote: https://gitlab.com/bonsai-oss/organization/ci-templates/-/raw/main/templates/language/go.yml
  - remote: https://gitlab.com/bonsai-oss/organization/ci-templates/-/raw/main/templates/release/semver.yml

build-initrd:
  stage: build
  image: archlinux:base
  before_script:
    - mkdir -p cache >/dev/null
    - cp -a cache/* /var/cache/pacman/pkg/ || true
    - pacman -Syy --noconfirm base-devel rsync wget go gzip cpio
    - cp -a /var/cache/pacman/pkg/* cache/ >/dev/null
  script:
    - make build
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - cache/
  artifacts:
    paths:
      - rootfs.cpio.gz

rollout:
  stage: integration-test
  needs:
    - build-initrd
  dependencies:
    - build-initrd
  tags:
    - miniland-vm-runner
  script:
    - cp -av rootfs.cpio.gz /proj/initrd/${CI_COMMIT_REF_SLUG}.cpio.gz
    - sudo virsh destroy Miniland || true
    - sudo virsh start Miniland