---
global:
  scrape_interval: 5s
  external_labels:
    instance: miniland
    stats_instance: miniland
scrape_configs:
- job_name: prometheus
  metrics_path: "/metrics"
  static_configs:
  - targets:
    - '[::1]:9090'
- job_name: node_exporter
  metrics_path: "/metrics"
  static_configs:
  - targets:
    - '[::1]:9100'
